spring.application.name=taskmanager v1
spring.config.import=optional:secret.properties

# Las variables de entorno(por ej: ${postgresql_url}) se obtienen de un archivo 'secret.properties' ver archivo 'ejemplo.properties.txt' para mas info
spring.datasource.url=${postgresql_url}
spring.datasource.username=${postgresql_username}
spring.datasource.password=${postgresql_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto= update

#Cors(url/localhost del frontend)
cors.url=${cors_url}

#Swagger config : url endpoints doc -> http://localhost:8080/swagger-ui/index.html
springdoc.api-docs.path=/api-docs